### ISSUE TITLE
Google Docs - Libre Barcode 128/39 

### ISSUE THREAD

**Issue by Jout8** [graphicore/librebarcode#25]
Hello.  I'm having issues getting Libre Barcode 128 to scan in Google docs.  I can scan in Google sheets when referencing another cell but not in a document file.  Is there something I could be missing?

**Comment by dad-attitude** [comment]
Hey I'm having the same issue, actually couldn't get any of the Libre Barcode fonts to create a scannable barcode in Google Docs. I got it working fine in Sheets and Slides. I did file feedback with Google but their screenshot tool would not capture the barcode properly.  It appears that in Docs extra bars are inserted on any text entered. I am attaching a screenshot. On the Docs barcode (highlighted in blue) there is an unselectable section of bars that get added to every line. Underneath I have included a screenshot of the same barcode in Sheets that does not have the extra bars and is scannable.
![docs vs sheets barcodes](https://user-images.githubusercontent.com/52460103/82050824-cac65100-9686-11ea-812e-fc57064ba0f2.png)

**Comment by graphicore** [comment]
Thanks for reporting. Sorry I'm really busy right now, but I'll look into it.

@dad-attitude you are using Code 39 here, right?

**Comment by dad-attitude** [comment]
Yes, all the code 39 barcodes in Docs had the same result for me. The excess bars get appended to any text entered. I assumed it might need to be fixed on the Google side (since the fonts work fine in Sheets and Slides) but wasn't sure and their support process is kind of nebulous so I figured I would also add my info here on the existing related issue. The Sheets/Slides workaround solved my problem in the meantime. Thanks so much!

**Comment by graphicore** [comment]
Here's a doc:

https://docs.google.com/document/d/1CqUJlu65NlNaDAfMTDhU8Acnw3dkKwNBZthH-CzreLA/edit?usp=sharing

Ha! Interesting, at first I was going to write:

> @dad-attitude, @Jout8: I think I can't reproduce any of the reported cases. Please share docs with your failing cases. And also browsers and version in case that is relevant.
>
> ![Screenshot from 2020-05-18 22-23-51](https://user-images.githubusercontent.com/393132/82256884-642b8680-9957-11ea-8725-bdee2f663ff1.png)
>
> I used here Firefox on openSUSE 75.0 (64-bit)

But, with Chromium Browser Version 81.0.4044.129 (openSUSE Build) (64-bit) I actually **can reproduce the issue!**:

![Screenshot from 2020-05-18 22-34-30](https://user-images.githubusercontent.com/393132/82257164-dd2ade00-9957-11ea-98f8-89c2fee0b659.png)


Using the web inspector in each browser, I can Identify an element `span.goog-inline-block` that in case of chrome ads a printed character and afterwards one more printed character. In Firefox, the same element is present but not printing. 

![Screenshot from 2020-05-18 23-25-13](https://user-images.githubusercontent.com/393132/82261670-c4bec180-995f-11ea-93db-ea89f56aea58.png)

Libre barcode also prints white space characters (space, non breaking space), because space is encoded in these barcode styles and prior existing barcode fonts are doing the same. Some software handles this better than other, obviously. I'm pretty sure this could be worked around or fixed in Google Docs, but maybe the underlying problem is in Chrome/Chromium/Blink or so.

It seems that in Chrome there is a "zero width non joiner" (`&zwnj;`) added at the end of the barcode styled text, might be the same in Firefox, but I suspect that Chrome renders white space like these characters using the space character of the font, which it shouldn't for obvious reasons. But a (naive) programmer may be tempted to think that a space char is always a blank glyph and just "draws" it in such a case.

I tried to fix it in the doc, by going to the end of the barcode and select Format->Clear Formatting and it made things a bit better, but the one misprinted space glyph coming probably from that `&zwnj;` can't be removed.

![Screenshot from 2020-05-18 23-34-57](https://user-images.githubusercontent.com/393132/82261936-4282cd00-9960-11ea-8954-6ea81c5ab84f.png)

When I remove the `&zwnj;` it in the DOM, with the inspector, I get the indendet result. **However, that's just proving that there's a space glyph drawn where it shouldn't, it doesn't change or fix the actual document and it can't be shared like this with other people.**

![Screenshot from 2020-05-18 23-39-26](https://user-images.githubusercontent.com/393132/82262278-e5d3e200-9960-11ea-948c-32f9989b6eb0.png)

**Comment by graphicore** [comment]
I will try to only have drawing space characters between start/end symbols using OTF substitution. Then, the default space could be blank. Will be hard to test in an live app before release though.

**Comment by graphicore** [comment]
Just a note: this should be fixed, but the updates in Google Fonts are still underway.

I tested this with locally installed versions of the fonts, which the browser preferred over the versions hosted by Google Fonts, that's why I'm pretty confident it's fixed.

**Comment by graphicore** [comment]
The updated fonts are now live on Google Fonts and thus Google Docs etc. works on Chrome.

**Comment by evanomondi** [comment]
Is there a specific fix I should look out for? Im still having this issue. I also tried using some guidance from this article https://www.barcodefaq.com/knowledge-base/scan-font/ but I'm still not able to scan the barcode.
![image](https://user-images.githubusercontent.com/4000840/120774739-3f3a8f00-c52b-11eb-8599-19c7e3a14ca0.png)

**Comment by graphicore** [comment]
@evanomondi please have a look at the docs to learn how to use the Libre Barcode fonts, e.g. for Code 39: https://graphicore.github.io/librebarcode/documentation/code39 If that doesn't help, I'll need more information from you to understand what your actual issue is. The linked article is not associated with this project.
